baseurl = "https://foss-ag.de/home"
title = "Free and Open-Source Software AG"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = ""
  copyright = "FOSS-AG"
  # have to be one line!
  sidebarAbout = [
    "<p>Aktuelle Organisations-Treffen<br>- 14.07.2017 / 14-16 Uhr / OH14 E33 (Treffen 45)<br>- 21.07.2017 / 14-16 Uhr / OH14 E33 (Treffen 46)</p>"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "https://postamt.cs.uni-dortmund.de/mailman/listinfo/foss-ag"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Startseite"
  url = "/"

  [[params.navlinks]]
  name = "Projekte"
  url = "projects/"

  [[params.navlinks]]
  name = "Social Media"
  url = "social_media/"

  [[params.navlinks]]
  name = "Links"
  url = "links/"

  [[params.navlinks]]
  name = "Protokolle"
  url = "protocols/"

  [[params.navlinks]]
  name = "Über uns"
  url = "about/"

  [params.social]
  twitter       = "https://twitter.com/fossagtudo"
  github        = "https://github.com/foss-ag"
  email         = "https://postamt.cs.uni-dortmund.de/mailman/listinfo/foss-ag"
  telegram      = "FOSS"
